theme: jekyll-theme-minimal
title: Theme Builder homepage
description: Create themes for your AEM Websites
lsi: false
safe: true
source: https://github.com/V-ishnuvarthan/theme-builder/
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
